baseURL = 'https://monicaph.github.io/mobileaffectivecomputing.github.io/'
languageCode = 'en-us'
title = 'Mobile Affective Computing'
theme = 'hugo-flex'

publishDir = 'docs'

[menus]
[[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 1
[[menus.main]]
    name = 'Posts'
    pageRef = '/post'
    weight = 2
#[[menus.main]]
#    name = ''
#    pageRef = '/post'
#    weight = 3

