baseURL = 'https://mobilehci-24-acimt.github.io/mobileaffectivecomputing.github.io/'
languageCode = 'en-us'
title = 'Affective Computing for Mobile Technologies'
theme = 'hugo-flex'

publishDir = 'docs'

[menus]
[[menus.main]]
    name = 'Home'
    pageRef = '/home'
    weight = 1
[[menus.main]]
    name = 'Keynote'
    pageRef = '/keynote'
    weight = 2
[[menus.main]]
    name = 'Call for Papers'
    pageRef = '/call'
    weight = 3
[[menus.main]]
    name = 'Organizers'
    pageRef = '/organizers'
    weight = 4
[[menus.main]]
    name = 'Contact'
    pageRef = '/contact'
    weight = 5

